export const animations = {
  // Locomotion animations
  F_CROUCH_STRAFE_LEFT: '/animations/locomotion/F_Crouch_Strafe_Left.glb',
  F_CROUCH_STRAFE_RIGHT: '/animations/locomotion/F_Crouch_Strafe_Right.glb',
  F_CROUCH_WALK_001: '/animations/locomotion/F_Crouch_Walk_001.glb',
  F_CROUCHEDWALK_BACKWARDS_001: '/animations/locomotion/F_CrouchedWalk_Backwards_001.glb',
  F_FALLING_IDLE_000: '/animations/locomotion/F_Falling_Idle_000.glb',
  F_FALLING_IDLE_001: '/animations/locomotion/F_Falling_Idle_001.glb',
  F_JOG_001: '/animations/locomotion/F_Jog_001.glb',
  F_JOG_BACKWARDS_001: '/animations/locomotion/F_Jog_Backwards_001.glb',
  F_JOG_JUMP_SMALL_001: '/animations/locomotion/F_Jog_Jump_Small_001.glb',
  F_JOG_STRAFE_LEFT_002: '/animations/locomotion/F_Jog_Strafe_Left_002.glb',
  F_JOG_STRAFE_RIGHT_002: '/animations/locomotion/F_Jog_Strafe_Right_002.glb',
  F_RUN_001: '/animations/locomotion/F_Run_001.glb',
  F_RUN_BACKWARDS_001: '/animations/locomotion/F_Run_Backwards_001.glb',
  F_RUN_JUMP_001: '/animations/locomotion/F_Run_Jump_001.glb',
  F_RUN_STRAFE_LEFT_001: '/animations/locomotion/F_Run_Strafe_Left_001.glb',
  F_RUN_STRAFE_RIGHT_001: '/animations/locomotion/F_Run_Strafe_Right_001.glb',
  F_WALK_002: '/animations/locomotion/F_Walk_002.glb',
  F_WALK_003: '/animations/locomotion/F_Walk_003.glb',
  F_WALK_BACKWARDS_001: '/animations/locomotion/F_Walk_Backwards_001.glb',
  F_WALK_JUMP_001: '/animations/locomotion/F_Walk_Jump_001.glb',
  F_WALK_JUMP_002: '/animations/locomotion/F_Walk_Jump_002.glb',
  F_WALK_STRAFE_LEFT_001: '/animations/locomotion/F_Walk_Strafe_Left_001.glb',
  F_WALK_STRAFE_RIGHT_001: '/animations/locomotion/F_Walk_Strafe_Right_001.glb',
  M_CROUCH_STRAFE_LEFT_002: '/animations/locomotion/M_Crouch_Strafe_Left_002.glb',
  M_CROUCH_STRAFE_RIGHT_002: '/animations/locomotion/M_Crouch_Strafe_Right_002.glb',
  M_CROUCH_WALK_003: '/animations/locomotion/M_Crouch_Walk_003.glb',
  M_CROUCHEDWALK_BACKWARDS_002: '/animations/locomotion/M_CrouchedWalk_Backwards_002.glb',
  M_FALLING_IDLE_002: '/animations/locomotion/M_Falling_Idle_002.glb',
  M_JOG_001: '/animations/locomotion/M_Jog_001.glb',
  M_JOG_003: '/animations/locomotion/M_Jog_003.glb',
  M_JOG_BACKWARDS_001: '/animations/locomotion/M_Jog_Backwards_001.glb',
  M_JOG_JUMP_001: '/animations/locomotion/M_Jog_Jump_001.glb',
  M_JOG_JUMP_002: '/animations/locomotion/M_Jog_Jump_002.glb',
  M_JOG_STRAFE_LEFT_001: '/animations/locomotion/M_Jog_Strafe_Left_001.glb',
  M_JOG_STRAFE_RIGHT_001: '/animations/locomotion/M_Jog_Strafe_Right_001.glb',
  M_RUN_001: '/animations/locomotion/M_Run_001.glb',
  M_RUN_BACKWARDS_002: '/animations/locomotion/M_Run_Backwards_002.glb',
  M_RUN_JUMP_001: '/animations/locomotion/M_Run_Jump_001.glb',
  M_RUN_JUMP_002: '/animations/locomotion/M_Run_Jump_002.glb',
  M_RUN_STRAFE_LEFT_002: '/animations/locomotion/M_Run_Strafe_Left_002.glb',
  M_RUN_STRAFE_RIGHT_002: '/animations/locomotion/M_Run_Strafe_Right_002.glb',
  M_WALK_001: '/animations/locomotion/M_Walk_001.glb',
  M_WALK_002: '/animations/locomotion/M_Walk_002.glb',
  M_WALK_BACKWARDS_001: '/animations/locomotion/M_Walk_Backwards_001.glb',
  M_WALK_JUMP_001: '/animations/locomotion/M_Walk_Jump_001.glb',
  M_WALK_JUMP_002: '/animations/locomotion/M_Walk_Jump_002.glb',
  M_WALK_JUMP_003: '/animations/locomotion/M_Walk_Jump_003.glb',
  M_WALK_STRAFE_LEFT_002: '/animations/locomotion/M_Walk_Strafe_Left_002.glb',
  M_WALK_STRAFE_RIGHT_002: '/animations/locomotion/M_Walk_Strafe_Right_002.glb',

  // Dance animations
  F_DANCES_001: '/animations/dance/F_Dances_001.glb',
  F_DANCES_004: '/animations/dance/F_Dances_004.glb',
  F_DANCES_005: '/animations/dance/F_Dances_005.glb',
  F_DANCES_006: '/animations/dance/F_Dances_006.glb',
  F_DANCES_007: '/animations/dance/F_Dances_007.glb',
  M_DANCES_001: '/animations/dance/M_Dances_001.glb',
  M_DANCES_002: '/animations/dance/M_Dances_002.glb',
  M_DANCES_003: '/animations/dance/M_Dances_003.glb',
  M_DANCES_004: '/animations/dance/M_Dances_004.glb',
  M_DANCES_005: '/animations/dance/M_Dances_005.glb',
  M_DANCES_006: '/animations/dance/M_Dances_006.glb',
  M_DANCES_007: '/animations/dance/M_Dances_007.glb',
  M_DANCES_008: '/animations/dance/M_Dances_008.glb',
  M_DANCES_009: '/animations/dance/M_Dances_009.glb',
  M_DANCES_011: '/animations/dance/M_Dances_011.glb',

  // Idle animations
  F_STANDING_IDLE_001: '/animations/idle/F_Standing_Idle_001.glb',
  F_STANDING_IDLE_VARIATIONS_001: '/animations/idle/F_Standing_Idle_Variations_001.glb',
  F_STANDING_IDLE_VARIATIONS_002: '/animations/idle/F_Standing_Idle_Variations_002.glb',
  F_STANDING_IDLE_VARIATIONS_003: '/animations/idle/F_Standing_Idle_Variations_003.glb',
  F_STANDING_IDLE_VARIATIONS_004: '/animations/idle/F_Standing_Idle_Variations_004.glb',
  F_STANDING_IDLE_VARIATIONS_005: '/animations/idle/F_Standing_Idle_Variations_005.glb',
  F_STANDING_IDLE_VARIATIONS_006: '/animations/idle/F_Standing_Idle_Variations_006.glb',
  F_STANDING_IDLE_VARIATIONS_007: '/animations/idle/F_Standing_Idle_Variations_007.glb',
  F_STANDING_IDLE_VARIATIONS_008: '/animations/idle/F_Standing_Idle_Variations_008.glb',
  F_STANDING_IDLE_VARIATIONS_009: '/animations/idle/F_Standing_Idle_Variations_009.glb',
  M_STANDING_IDLE_001: '/animations/idle/M_Standing_Idle_001.glb',
  M_STANDING_IDLE_002: '/animations/idle/M_Standing_Idle_002.glb',
  M_STANDING_IDLE_VARIATIONS_001: '/animations/idle/M_Standing_Idle_Variations_001.glb',
  M_STANDING_IDLE_VARIATIONS_002: '/animations/idle/M_Standing_Idle_Variations_002.glb',
  M_STANDING_IDLE_VARIATIONS_003: '/animations/idle/M_Standing_Idle_Variations_003.glb',
  M_STANDING_IDLE_VARIATIONS_004: '/animations/idle/M_Standing_Idle_Variations_004.glb',
  M_STANDING_IDLE_VARIATIONS_005: '/animations/idle/M_Standing_Idle_Variations_005.glb',
  M_STANDING_IDLE_VARIATIONS_006: '/animations/idle/M_Standing_Idle_Variations_006.glb',
  M_STANDING_IDLE_VARIATIONS_007: '/animations/idle/M_Standing_Idle_Variations_007.glb',
  M_STANDING_IDLE_VARIATIONS_008: '/animations/idle/M_Standing_Idle_Variations_008.glb',
  M_STANDING_IDLE_VARIATIONS_009: '/animations/idle/M_Standing_Idle_Variations_009.glb',
  M_STANDING_IDLE_VARIATIONS_010: '/animations/idle/M_Standing_Idle_Variations_010.glb',

  // Expression animations
  F_TALKING_VARIATIONS_001: '/animations/expression/F_Talking_Variations_001.glb',
  F_TALKING_VARIATIONS_002: '/animations/expression/F_Talking_Variations_002.glb',
  F_TALKING_VARIATIONS_003: '/animations/expression/F_Talking_Variations_003.glb',
  F_TALKING_VARIATIONS_004: '/animations/expression/F_Talking_Variations_004.glb',
  F_TALKING_VARIATIONS_005: '/animations/expression/F_Talking_Variations_005.glb',
  F_TALKING_VARIATIONS_006: '/animations/expression/F_Talking_Variations_006.glb',
  M_STANDING_EXPRESSIONS_001: '/animations/expression/M_Standing_Expressions_001.glb',
  M_STANDING_EXPRESSIONS_002: '/animations/expression/M_Standing_Expressions_002.glb',
  M_STANDING_EXPRESSIONS_004: '/animations/expression/M_Standing_Expressions_004.glb',
  M_STANDING_EXPRESSIONS_005: '/animations/expression/M_Standing_Expressions_005.glb',
  M_STANDING_EXPRESSIONS_006: '/animations/expression/M_Standing_Expressions_006.glb',
  M_STANDING_EXPRESSIONS_007: '/animations/expression/M_Standing_Expressions_007.glb',
  M_STANDING_EXPRESSIONS_008: '/animations/expression/M_Standing_Expressions_008.glb',
  M_STANDING_EXPRESSIONS_009: '/animations/expression/M_Standing_Expressions_009.glb',
  M_STANDING_EXPRESSIONS_010: '/animations/expression/M_Standing_Expressions_010.glb',
  M_STANDING_EXPRESSIONS_011: '/animations/expression/M_Standing_Expressions_011.glb',
  M_STANDING_EXPRESSIONS_012: '/animations/expression/M_Standing_Expressions_012.glb',
  M_STANDING_EXPRESSIONS_013: '/animations/expression/M_Standing_Expressions_013.glb',
  M_STANDING_EXPRESSIONS_014: '/animations/expression/M_Standing_Expressions_014.glb',
  M_STANDING_EXPRESSIONS_015: '/animations/expression/M_Standing_Expressions_015.glb',
  M_STANDING_EXPRESSIONS_016: '/animations/expression/M_Standing_Expressions_016.glb',
  M_STANDING_EXPRESSIONS_017: '/animations/expression/M_Standing_Expressions_017.glb',
  M_STANDING_EXPRESSIONS_018: '/animations/expression/M_Standing_Expressions_018.glb',
  M_TALKING_VARIATIONS_001: '/animations/expression/M_Talking_Variations_001.glb',
  M_TALKING_VARIATIONS_002: '/animations/expression/M_Talking_Variations_002.glb',
  M_TALKING_VARIATIONS_003: '/animations/expression/M_Talking_Variations_003.glb',
  M_TALKING_VARIATIONS_004: '/animations/expression/M_Talking_Variations_004.glb',
  M_TALKING_VARIATIONS_005: '/animations/expression/M_Talking_Variations_005.glb',
  M_TALKING_VARIATIONS_006: '/animations/expression/M_Talking_Variations_006.glb',
  M_TALKING_VARIATIONS_007: '/animations/expression/M_Talking_Variations_007.glb',
  M_TALKING_VARIATIONS_008: '/animations/expression/M_Talking_Variations_008.glb',
  M_TALKING_VARIATIONS_009: '/animations/expression/M_Talking_Variations_009.glb',
  M_TALKING_VARIATIONS_010: '/animations/expression/M_Talking_Variations_010.glb',
} as const;

export type AnimationKey = keyof typeof animations;


export const animationItems = [
  {
    id: "anim1",
    name: "Wave",
    animation: "wave"
  },
  {
    id: "anim2",
    name: "Jump",
    animation: "jump"
  },
  {
    id: "anim3",
    name: "Dance",
    animation: "dance"
  },
  {
    id: "anim4",
    name: "Idle",
    animation: "idle"
  },
  {
    id: "anim5",
    name: "Walk",
    animation: "walk"
  },
  {
    id: "anim6",
    name: "Run",
    animation: "run"
  },
  // Add more animation items as needed
];

