export const menuItems = {
  en: {
    home: "Home",
    settings: "Settings",
    termsAndPrivacy: "Terms & Privacy",
    billingAndSubscription: "Billing & Subscription",
    logout: "Log out",
    language: "Language",
    upgradePlan: "Upgrade Plan",
    login: "Login",
  },
  es: {
    home: "Inicio",
    settings: "Configuración",
    termsAndPrivacy: "Términos y Privacidad",
    billingAndSubscription: "Facturación y Suscripción",
    logout: "Cerrar Sesión",
    language: "Idioma",
    upgradePlan: "Mejorar Plan",
    login: "Iniciar Sesión",
  },
  it: {
    home: "Home",
    settings: "Impostazioni",
    termsAndPrivacy: "Termini e Privacy",
    billingAndSubscription: "Fatturazione e Abbonamento",
    logout: "Esci",
    language: "Lingua",
    upgradePlan: "Aggiorna Piano",
    login: "Accedi",
  },
  fr: {
    home: "Accueil",
    settings: "Paramètres",
    termsAndPrivacy: "Conditions et Confidentialité",
    billingAndSubscription: "Facturation et Abonnement",
    logout: "Déconnexion",
    language: "Langue",
    upgradePlan: "Améliorer l'abonnement",
    login: "Connexion",
  },
  de: {
    home: "Startseite",
    settings: "Einstellungen",
    termsAndPrivacy: "Bedingungen & Datenschutz",
    billingAndSubscription: "Abrechnung & Abonnement",
    logout: "Abmelden",
    language: "Sprache",
    upgradePlan: "Plan upgraden",
    login: "Anmelden",
  },
  ja: {
    home: "ホーム",
    settings: "設定",
    termsAndPrivacy: "利用規約・プライバシー",
    billingAndSubscription: "請求・購読",
    logout: "ログアウト",
    language: "言語",
    upgradePlan: "プランをアップグレード",
    login: "ログイン",
  },
  ko: {
    home: "홈",
    settings: "설정",
    termsAndPrivacy: "이용약관 및 개인정보",
    billingAndSubscription: "결제 및 구독",
    logout: "로그아웃",
    language: "언어",
    upgradePlan: "플랜 업그레이드",
    login: "로그인",
  },
  zh: {
    home: "首页",
    settings: "设置",
    termsAndPrivacy: "条款和隐私",
    billingAndSubscription: "账单和订阅",
    logout: "退出登录",
    language: "语言",
    upgradePlan: "升级计划",
    login: "登录",
  },
  hi: {
    home: "होम",
    settings: "सेटिंग्स",
    termsAndPrivacy: "नियम और गोपनीयता",
    billingAndSubscription: "बिलिंग और सदस्यता",
    logout: "लॉग आउट",
    language: "भाषा",
    upgradePlan: "प्लान अपग्रेड करें",
    login: "लॉगिन",
  },
  pt: {
    home: "Início",
    settings: "Configurações",
    termsAndPrivacy: "Termos e Privacidade",
    billingAndSubscription: "Faturamento e Assinatura",
    logout: "Sair",
    language: "Idioma",
    upgradePlan: "Atualizar Plano",
    login: "Entrar",
  },
  ar: {
    home: "الرئيسية",
    settings: "الإعدادات",
    termsAndPrivacy: "الشروط والخصوصية",
    billingAndSubscription: "الفواتير والاشتراك",
    logout: "تسجيل الخروج",
    language: "اللغة",
    upgradePlan: "ترقية الخطة",
    login: "تسجيل الدخول",
  },
}